package certs

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/laoshan-tech/tyz/apps/agent/internal/model"
)

// fixture.json is generated by the control plane's DER encoder (see
// apps/server/scripts/gen-tls-fixture.ts). Parsing it here with crypto/x509
// cross-checks the Workers-side encoder against a real X.509 implementation:
// chain building, SAN, EKU and key usability must all verify.
type fixture struct {
	SNI        string `json:"sni"`
	CACert     string `json:"ca_cert"`
	ServerCert string `json:"server_cert"`
	ServerKey  string `json:"server_key"`
	ClientCert string `json:"client_cert"`
	ClientKey  string `json:"client_key"`
}

func loadFixture(t *testing.T) fixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "fixture.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	return f
}

func parseCert(t *testing.T, pemText string) *x509.Certificate {
	t.Helper()
	block, _ := pem.Decode([]byte(pemText))
	if block == nil {
		t.Fatalf("no PEM block found")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatalf("parse certificate: %v", err)
	}
	return cert
}

func parseKey(t *testing.T, pemText string) any {
	t.Helper()
	block, _ := pem.Decode([]byte(pemText))
	if block == nil {
		t.Fatalf("no PEM block found")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		t.Fatalf("parse PKCS8 key: %v", err)
	}
	return key
}

func TestFixtureChainsAndExtensions(t *testing.T) {
	f := loadFixture(t)
	ca := parseCert(t, f.CACert)
	server := parseCert(t, f.ServerCert)
	client := parseCert(t, f.ClientCert)

	if !ca.IsCA || ca.Subject.CommonName == "" {
		t.Fatalf("CA cert lacks CA flag or subject")
	}
	if err := server.CheckSignatureFrom(ca); err != nil {
		t.Fatalf("server cert not signed by CA: %v", err)
	}
	if err := client.CheckSignatureFrom(ca); err != nil {
		t.Fatalf("client cert not signed by CA: %v", err)
	}

	roots := x509.NewCertPool()
	roots.AddCert(ca)
	if _, err := server.Verify(x509.VerifyOptions{Roots: roots, DNSName: f.SNI}); err != nil {
		t.Fatalf("server chain does not verify for SNI %s: %v", f.SNI, err)
	}
	if _, err := client.Verify(x509.VerifyOptions{Roots: roots, KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth}}); err != nil {
		t.Fatalf("client chain does not verify for clientAuth: %v", err)
	}

	if server.DNSNames == nil || server.DNSNames[0] != f.SNI {
		t.Fatalf("server SAN = %v, want [%s]", server.DNSNames, f.SNI)
	}
	hasServerAuth := false
	for _, eku := range server.ExtKeyUsage {
		if eku == x509.ExtKeyUsageServerAuth {
			hasServerAuth = true
		}
	}
	if !hasServerAuth {
		t.Fatalf("server cert lacks serverAuth EKU")
	}

	serverKey := parseKey(t, f.ServerKey).(*ecdsa.PrivateKey)
	if serverKey.Curve != elliptic.P256() {
		t.Fatalf("server key curve = %v, want P-256", serverKey.Curve)
	}
	serverPub, ok := server.PublicKey.(*ecdsa.PublicKey)
	if !ok || !serverPub.Equal(&serverKey.PublicKey) {
		t.Fatalf("server cert/key mismatch")
	}

	// TLS-relevant window sanity: leaves must be valid for ~a year from now.
	if time.Until(server.NotAfter) < 300*24*time.Hour {
		t.Fatalf("server cert validity too short: notAfter=%s", server.NotAfter)
	}
}

func TestEnsureWritesAndSkipsUnchanged(t *testing.T) {
	f := loadFixture(t)
	dir := t.TempDir()
	material := &model.TLSMaterial{
		SNI:        f.SNI,
		CACert:     f.CACert,
		ServerCert: f.ServerCert,
		ServerKey:  f.ServerKey,
		ClientCert: f.ClientCert,
		ClientKey:  f.ClientKey,
	}
	if err := Ensure(dir, material); err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	for _, name := range []string{CACertFile, ServerCert, ServerKey, ClientCert, ClientKey} {
		info, err := os.Stat(filepath.Join(Path(dir), name))
		if err != nil {
			t.Fatalf("stat %s: %v", name, err)
		}
		if info.Mode().Perm() != filePerm {
			t.Fatalf("%s perm = %v, want %v", name, info.Mode().Perm(), filePerm)
		}
	}

	// Re-ensure with identical content must not rewrite (mtime stable).
	before, _ := os.Stat(filepath.Join(Path(dir), ServerCert))
	time.Sleep(10 * time.Millisecond)
	if err := Ensure(dir, material); err != nil {
		t.Fatalf("re-Ensure: %v", err)
	}
	after, _ := os.Stat(filepath.Join(Path(dir), ServerCert))
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatalf("unchanged material was rewritten")
	}

	// Changed content must land on disk.
	material.ServerCert = f.ClientCert
	if err := Ensure(dir, material); err != nil {
		t.Fatalf("Ensure after change: %v", err)
	}
	got, _ := os.ReadFile(filepath.Join(Path(dir), ServerCert))
	if string(got) != f.ClientCert {
		t.Fatalf("changed PEM not written")
	}

	// nil material is a no-op.
	if err := Ensure(dir, nil); err != nil {
		t.Fatalf("Ensure(nil): %v", err)
	}
}
