package builder

import (
	"encoding/json"
	"flag"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/go-gost/x/config"
	"github.com/laoshan-tech/tyz-node/apps/agent/internal/model"
)

const (
	examplePath = "../../../../examples/real-database-example.json"
	goldenPath  = "testdata/golden-gost-config.json"
)

var updateGoldens = flag.Bool("update", false, "rewrite golden files instead of comparing")

// TestBuildGolden pins the Go builder's output to the TypeScript builder's
// output for examples/real-database-example.json (generated by the TS agent
// before the migration; see apps/agent/scripts/gen-golden.ts history).
//
// Two deliberate, documented deltas are normalized away before comparing:
//   - nodes[].tls{validity,commonName,organization}: the old agent emitted
//     auto-cert parameters there, but GOST's NodeConfig.tls (TLSNodeConfig)
//     has never had those fields — they were silently dropped by GOST. The Go
//     builder feeds them to the global default certificate instead
//     (DefaultTLS + parsing.BuildDefaultTLSConfig).
//   - selector.failTimeout: the TS agent emitted bare seconds (30); Go
//     marshals time.Duration as nanoseconds (30000000000). Both normalize to
//     seconds.
func TestBuildGolden(t *testing.T) {
	data := loadExample(t)

	got, err := Build(data)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	gotJSON, err := json.Marshal(got)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	rawGolden, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}

	var gotTree, goldenTree any
	if err := json.Unmarshal(gotJSON, &gotTree); err != nil {
		t.Fatalf("unmarshal got: %v", err)
	}
	if err := json.Unmarshal(rawGolden, &goldenTree); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}

	dropInertNodeTLS(t, goldenTree)
	normalizeSelectorDurations(gotTree)
	normalizeSelectorDurations(goldenTree)

	if *updateGoldens {
		rewriteGolden(t, goldenPath, got)
		return
	}
	if !reflect.DeepEqual(gotTree, goldenTree) {
		prettyGot, _ := json.MarshalIndent(gotTree, "", "  ")
		prettyGolden, _ := json.MarshalIndent(goldenTree, "", "  ")
		t.Fatalf("generated config differs from golden baseline.\n--- got ---\n%s\n--- golden ---\n%s", prettyGot, prettyGolden)
	}
}

// TestBuildTwoNodeGolden pins the two-node relay scenario (mirrors a real
// production deployment): the entry renders one service per rule sharing a
// single chain; the exit renders ONE relay listener (service-t{tunnelId})
// with no per-rule limiters, and its port is independent of the entry ports.
func TestBuildTwoNodeGolden(t *testing.T) {
	raw, err := os.ReadFile("testdata/two-node-example.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fixture struct {
		Entry *model.NodeConfigData `json:"entry"`
		Exit  *model.NodeConfigData `json:"exit"`
	}
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}

	entryCfg, err := Build(fixture.Entry)
	if err != nil {
		t.Fatalf("build entry: %v", err)
	}
	exitCfg, err := Build(fixture.Exit)
	if err != nil {
		t.Fatalf("build exit: %v", err)
	}

	compareOrRewrite(t, entryCfg, "testdata/two-node-golden-entry.json")
	compareOrRewrite(t, exitCfg, "testdata/two-node-golden-exit.json")

	// Shape assertions for the properties the golden alone renders awkwardly.
	if len(entryCfg.Services) != 2 {
		t.Fatalf("entry services = %d, want one per rule (2)", len(entryCfg.Services))
	}
	if len(entryCfg.Chains) != 1 {
		t.Fatalf("entry chains = %d, want a single shared chain", len(entryCfg.Chains))
	}
	if len(exitCfg.Services) != 1 {
		t.Fatalf("exit services = %d, want a single relay listener for both rules", len(exitCfg.Services))
	}
	if exitCfg.Services[0].Name != "service-t2" || exitCfg.Services[0].Addr != ":46900" {
		t.Fatalf("exit service = %s %s, want service-t2 :46900", exitCfg.Services[0].Name, exitCfg.Services[0].Addr)
	}
	if exitCfg.Services[0].Handler.Type != "relay" {
		t.Fatalf("exit handler = %s, want relay", exitCfg.Services[0].Handler.Type)
	}
	if len(exitCfg.Limiters) != 0 {
		t.Fatalf("exit limiters = %d, want 0 (limiters apply at the entry services)", len(exitCfg.Limiters))
	}
	if entryCfg.Services[0].Limiter == "" {
		t.Fatal("entry rule-2 should carry the traffic limiter")
	}
}

// compareOrRewrite normalizes and compares a generated config against a
// golden file (see TestBuildGolden for the normalization rationale), or
// rewrites the golden when -update is passed.
func compareOrRewrite(t *testing.T, got *config.Config, path string) {
	t.Helper()
	gotJSON, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	var gotTree any
	if err := json.Unmarshal(gotJSON, &gotTree); err != nil {
		t.Fatalf("unmarshal got: %v", err)
	}
	normalizeSelectorDurations(gotTree)

	if *updateGoldens {
		rewriteGolden(t, path, got)
		return
	}

	rawGolden, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var goldenTree any
	if err := json.Unmarshal(rawGolden, &goldenTree); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}
	normalizeSelectorDurations(goldenTree)

	if !reflect.DeepEqual(gotTree, goldenTree) {
		prettyGot, _ := json.MarshalIndent(gotTree, "", "  ")
		prettyGolden, _ := json.MarshalIndent(goldenTree, "", "  ")
		t.Fatalf("%s differs from golden.\n--- got ---\n%s\n--- golden ---\n%s", path, prettyGot, prettyGolden)
	}
}

func rewriteGolden(t *testing.T, path string, got *config.Config) {
	t.Helper()
	raw, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal golden: %v", err)
	}
	if err := os.WriteFile(path, append(raw, '\n'), 0o644); err != nil {
		t.Fatalf("write golden: %v", err)
	}
}

// dropInertNodeTLS removes nodes[].tls from the TS golden tree (see test doc).
func dropInertNodeTLS(t *testing.T, tree any) {
	t.Helper()
	root, ok := tree.(map[string]any)
	if !ok {
		t.Fatalf("golden root is %T, want map", tree)
	}
	chains, _ := root["chains"].([]any)
	for _, chainAny := range chains {
		chain, ok := chainAny.(map[string]any)
		if !ok {
			continue
		}
		for _, hopAny := range chain["hops"].([]any) {
			hop, ok := hopAny.(map[string]any)
			if !ok {
				continue
			}
			for _, nodeAny := range hop["nodes"].([]any) {
				if node, ok := nodeAny.(map[string]any); ok {
					delete(node, "tls")
				}
			}
		}
	}
}

// normalizeSelectorDurations converts failTimeout nanoseconds (Go marshal) to
// the seconds the TS builder emitted; values below 1s are already seconds.
func normalizeSelectorDurations(tree any) {
	switch node := tree.(type) {
	case map[string]any:
		for key, value := range node {
			if key == "failTimeout" {
				if v, ok := value.(float64); ok && v >= 1e9 {
					node[key] = v / 1e9
				}
				continue
			}
			normalizeSelectorDurations(value)
		}
	case []any:
		for _, item := range node {
			normalizeSelectorDurations(item)
		}
	}
}

func loadExample(t *testing.T) *model.NodeConfigData {
	t.Helper()
	raw, err := os.ReadFile(examplePath)
	if err != nil {
		t.Fatalf("read example: %v", err)
	}
	var wrapper struct {
		AggregatedData *model.NodeConfigData `json:"aggregated_data"`
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		t.Fatalf("parse example: %v", err)
	}
	if wrapper.AggregatedData == nil {
		t.Fatal("example has no aggregated_data")
	}
	return wrapper.AggregatedData
}

// TestDefaultTLS checks the control-plane TLS hints flow into the global
// default certificate parameters.
func TestDefaultTLS(t *testing.T) {
	if got := DefaultTLS(nil); got.CommonName != defaultCommonName || got.Organization != defaultOrganization || got.Validity != 8760*time.Hour {
		t.Fatalf("DefaultTLS(nil) = %+v", got)
	}
	cn, org := "relay.example.com", "ExampleOrg"
	got := DefaultTLS(&model.TlsConfig{CommonName: &cn, Organization: &org})
	if got.CommonName != cn || got.Organization != org {
		t.Fatalf("DefaultTLS(hints) = %+v", got)
	}
}

// TestChainAddrNodeResolution pins per-hop address resolution: each chain row
// resolves against its own node record (address + port range); payloads
// without the nodes list fall back to the recipient node.
func TestChainAddrNodeResolution(t *testing.T) {
	data := &model.NodeConfigData{
		Node: model.RelayNode{ID: 1, Address: "10.0.0.1", Ports: "10000-20000"},
		Nodes: []model.RelayNode{
			{ID: 1, Address: "10.0.0.1", Ports: "10000-20000"},
			{ID: 2, Address: "10.0.0.2", Ports: "20000-30000"},
		},
		Chains: []model.Chain{
			{ID: 7, TunnelID: 1, NodeID: 2, ChainType: model.ChainOut, Transport: model.TransportRaw, Port: 16900},
			{ID: 8, TunnelID: 1, NodeID: 2, ChainType: model.ChainOut, Transport: model.TransportRaw, Port: 0}, // allocate from node 2's range
		},
	}
	b := &cfgBuilder{data: data}

	got, err := b.chainAddr(&data.Chains[0])
	if err != nil || got != "10.0.0.2:16900" {
		t.Fatalf("chainAddr explicit port = %q, %v; want 10.0.0.2:16900", got, err)
	}
	got, err = b.chainAddr(&data.Chains[1])
	if err != nil || got != "10.0.0.2:20010" { // 20000 + (8+2) % 10001
		t.Fatalf("chainAddr allocated = %q, %v; want 10.0.0.2:20010", got, err)
	}

	// Legacy payload without nodes: fall back to the recipient's record.
	legacy := &model.NodeConfigData{
		Node:   model.RelayNode{ID: 1, Address: "10.0.0.1", Ports: "10000-20000"},
		Chains: []model.Chain{{ID: 9, TunnelID: 1, NodeID: 2, ChainType: model.ChainOut, Port: 16900}},
	}
	got, err = (&cfgBuilder{data: legacy}).chainAddr(&legacy.Chains[0])
	if err != nil || got != "10.0.0.1:16900" {
		t.Fatalf("legacy chainAddr = %q, %v; want 10.0.0.1:16900", got, err)
	}
}

// TestAllocatePortForChain pins the deterministic port formula.
func TestAllocatePortForChain(t *testing.T) {
	if got, err := allocatePortForChain("10000-20000", 5, 7); err != nil || got != 10012 {
		t.Fatalf("allocatePortForChain = %d, %v; want 10012, nil", got, err)
	}
	if _, err := allocatePortForChain("bogus", 1, 1); err == nil {
		t.Fatal("expected error for invalid range")
	}
}

// TestBuildNoTunnelForwarding covers the tunnel-less simple forwarding shape.
func TestBuildNoTunnelForwarding(t *testing.T) {
	data := &model.NodeConfigData{
		Node:  model.RelayNode{ID: 1, Address: "10.0.0.1", Ports: "20000-20010"},
		Rules: []model.RelayRule{{ID: 9, ListenPort: 38001, Targets: "example.com:80"}},
	}
	cfg, err := Build(data)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if len(cfg.Services) != 1 || cfg.Services[0].Name != "service-9" {
		t.Fatalf("services = %+v", cfg.Services)
	}
	svc := cfg.Services[0]
	if svc.Addr != ":38001" || svc.Handler.Type != "tcp" || svc.Listener.Type != "tcp" {
		t.Fatalf("service shape = %+v %+v", svc.Handler, svc.Listener)
	}
	if svc.Metadata["enableStats"] != "true" || svc.Observer != ObserverName {
		t.Fatalf("stats wiring missing: %+v", svc)
	}
	if len(cfg.Chains) != 0 {
		t.Fatalf("chains = %+v", cfg.Chains)
	}
}

// compile-time check that Build output is a *config.Config usable by gostapply.
var _ = func() *config.Config { c, _ := Build(&model.NodeConfigData{}); return c }
